Just for sanity check of the integrity of data provided by `EquityCalculator.exe`

In [40]:
# Read the equity matrix from the binary file and reshape it into a 169x169 matrix
import numpy as np
file_path: str = r".\equity_169x169_matrix.bin"
equity_matrix: np.ndarray = np.fromfile(file_path, dtype=np.float32)
equity_matrix = equity_matrix.reshape((169, 169))
np.set_printoptions(precision=4, suppress=True, linewidth=150)

sanity_check_matrix = equity_matrix[:10, :10]

print("=== Sanity Check: Top-left 10x10 Equity Matrix ===")
print(sanity_check_matrix)

=== Sanity Check: Top-left 10x10 Equity Matrix ===
[[0.5    0.8775 0.8745 0.8717 0.8667 0.8843 0.8799 0.8804 0.8822 0.8668]
 [0.1225 0.5    0.7139 0.7102 0.7061 0.7128 0.7101 0.7065 0.7083 0.699 ]
 [0.1255 0.2861 0.5    0.7103 0.7044 0.7068 0.704  0.7063 0.7038 0.6918]
 [0.1283 0.2898 0.2897 0.5    0.6996 0.7018 0.6975 0.6955 0.6986 0.684 ]
 [0.1333 0.2939 0.2956 0.3004 0.5    0.6917 0.6884 0.6856 0.6876 0.6756]
 [0.1157 0.2872 0.2932 0.2982 0.3083 0.5    0.6659 0.6644 0.6644 0.6513]
 [0.1201 0.2899 0.296  0.3025 0.3116 0.3341 0.5    0.6431 0.6443 0.6307]
 [0.1196 0.2935 0.2937 0.3045 0.3144 0.3356 0.3569 0.5    0.6157 0.6017]
 [0.1178 0.2917 0.2962 0.3014 0.3124 0.3356 0.3557 0.3843 0.5    0.5676]
 [0.1332 0.301  0.3082 0.316  0.3244 0.3487 0.3693 0.3983 0.4324 0.5   ]]


In [41]:
# specific hand equity checks
rank: dict[str, int] = {'A':0, 'K':1, 'Q':2, 'J':3, 'T':4, '9':5, '8':6, '7':7, '6':8, '5':9, '4':10, '3':11, '2':12}

hero_hand: str = "AKs"
villain_hand: str = "AXs"

def hand_to_index(hand: str) -> int:
    rank1, rank2 = hand[0], hand[1]
    idx1, idx2 = rank[rank1], rank[rank2]
    if idx1 == idx2:
        return idx1 * 13 + idx2
    elif hand[2] == 's':
        return min(idx1, idx2) * 13 + max(idx1, idx2)
    else:
        return max(idx1, idx2) * 13 + min(idx1, idx2)
hero_idx: int = hand_to_index(hero_hand)

for villain_ace_high in ['K', 'Q', 'J', 'T', '9', '8', '7', '6']:
    villain_hand = f"A{villain_ace_high}s"
    villain_idx = hand_to_index(villain_hand)
    print(f"Equity of {hero_hand} vs {villain_hand}: {equity_matrix[hero_idx, villain_idx]:.4f}")
    
print("    --- wheels below ---")
for villain_wheel in ['5', '4', '3', '2']:
    villain_hand = f"A{villain_wheel}s"
    villain_idx = hand_to_index(villain_hand)
    print(f"Equity of {hero_hand} vs {villain_hand}: {equity_matrix[hero_idx, villain_idx]:.4f}")

Equity of AKs vs AKs: 0.5000
Equity of AKs vs AQs: 0.7139
Equity of AKs vs AJs: 0.7102
Equity of AKs vs ATs: 0.7061
Equity of AKs vs A9s: 0.7128
Equity of AKs vs A8s: 0.7101
Equity of AKs vs A7s: 0.7065
Equity of AKs vs A6s: 0.7083
    --- wheels below ---
Equity of AKs vs A5s: 0.6990
Equity of AKs vs A4s: 0.7031
Equity of AKs vs A3s: 0.7079
Equity of AKs vs A2s: 0.7108
